<template>
  <v-container>
    <v-row class="text-center">
      <v-col>
        <h2 class="text-h4 font-weight-bold mb-3">
          Welcome to the Strat-O-Matic Football Standings Utility
        </h2>
        <p class="subheading font-weight-regular">
          This utility provides expanded standings for the Strat-O-Matic
          Football game. The additional information can be used to determine
          tiebreakers.<br /><br />
          The process requires two reports generated by the football game:
          League Standings and League Schedule.<br /><br />
          To generate these reports you need to be in League Manager and have
          the league opened. Go to Reports->League and run the Standings report
          and League Schedule report.<br /><br />
          Import these two reports using the form below. The reports are located
          in &lt;football install directory&gt;/LEAGUES/&lt;the current
          league&gt;/reports and are named leaguestandings.htm and
          leagueschedule.htm. The standings report does not need to be
          regenerated everytime. A stale version of this report can always be
          used. It is used only to get the league's structure. Nothing else is
          pulled from this report. The schedule report must be as current as
          possible since it will contain your league's game results. This is
          where all of the detail for the report is pulled from.<br /><br />
          When you see the report, you will notice each team's name is preceded
          by a '+' sign. You can click this to view the teams that that team
          beat, lost to, and tied. Click again to hide it. Looking at this
          information for multiple teams can be used for the common opponents
          tie breaker.
        </p>
      </v-col>
      <v-col cols="12">
        <v-btn color="primary" elevation="8" to="/upload">Get Started</v-btn>
      </v-col>
    </v-row>
  </v-container>
</template>

<script lang="ts">
import Vue from "vue";

export default Vue.extend({
  name: "Home",

  data: () => ({}),
});
</script>
